default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: contact-manager_development

  #username: contact-manager

  #password:

  #host: localhost

  #port: 5432

  #schema_search_path: myapp,sharedapp,public

  #min_messages: notice

test:
  <<: *default
  database: contact-manager_test

production:
  <<: *default
  database: contact-manager_production
  username: contact-manager
  password: <%= ENV['CONTACT-MANAGER_DATABASE_PASSWORD'] %>
