# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058ac70431788567a923682cdf8c7f31f9250dfaf2a18aa3e8e8f236e9a7d73afb352a968604f368dcbab04997133476520ed408174f742a466da7d0f036fa29

test:
  secret_key_base: cf152c51da940452d59e5af49adabbb896c1bb9d5197cdbe38485bff638bdc89e2c10962c978cf4e1a020815b3201908e0c3cb476b3f363ac68c7d1ba9ff47be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
